spring:
  application:
    name: payment-service
  mongodb:
    uri: ${MONGO_URI}
    representation:
      uuid: STANDARD
  data:
    redis:
      url: ${REDIS_URI}
      repositories:
        enabled: false
server:
  port: 8081